---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: remote_server
  become: true
  roles:
    - neutron
    - horizon
    - cinder
